Change rfr to use singbegin/pass/fail scripts

diff --git a/rfr b/rfr
--- a/rfr
+++ b/rfr
@@ -28,9 +28,9 @@ cirun
 #
 if [ "$SING" = 'y' ]; then
     echo 'SINGING SPECS ENABLED, YAY!!!'
-    say -v "Pipe Organ" "Sam Jackson says hang on to your butts" &
-    (time bundle exec rspec $@ && cipass && say -v "Good News" "Your specs are all passing" || (cifail && say -v "Bad News" "Your specs all fail you are bad you should feel bad" && exit -1))
+    singbegin
+    (time bundle exec rspec $@ && cipass && singpass || (cifail && singfail && exit -1)
 else
-    echo 'Non-singing specs'
+    echo 'Non-singing specs (you can turn them on with --sing as the first argument)'
     (time bundle exec rspec $@ && cipass || (cifail && exit -1))
 fi
